# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
    # Simple text replacement
    - trigger: ":espanso"
      replace: "Hi there!"

    # Dates
    - trigger: ":date"
      replace: "{{mydate}}"
      vars:
          - name: mydate
            type: date
            params:
                format: "%Y-%m-%d"

    # Shell commands
    - trigger: ":shell"
      replace: "{{output}}"
      vars:
          - name: output
            type: shell
            params:
                cmd: "echo Hello from your shell"

    - trigger: ":br"
      replace: "Best Regards,\nDileep"

    - trigger: ":now"
      replace: "{{mytime}}"
      vars:
          - name: mytime
            type: date
            params:
                format: "%H:%M"

    - trigger: ":ip"
      replace: "{{output}}"
      vars:
          - name: output
            type: shell
            params:
                cmd: "curl 'https://api.ipify.org'"

    - trigger: ":localip"
      replace: "{{output}}"
      vars:
          - name: output
            type: shell
            params:
                cmd: "ip a | grep 'inet 192' | awk '{ print $2 }'"

    - trigger: ":gmail"
      replace: "k.dileep1994@gmail.com"

    - trigger: ":bugmail"
      replace: "dkishore@bu.edu"

    - trigger: ":pm.me"
      replace: "dileep-kishore@protonmail.com"

    - trigger: ":dsegre_zoom"
      replace: "https://bostonu.zoom.us/j/91324569840?pwd=dytwMHdlb01Ia2xjdllPWHFkd25aZz09"

    - trigger: ":DPO"
      replace: "I am excited to get to work on this! \n \n## The big picture \n- Mission with deadline (Benefit to you and the world): \n- Curiosity (Scientific and programming): \n- Objective with deadline: \n- Outcome with deadline: \n- Helping/contributing to: \n- Duration: \nGet excited about the work! \n \n## Tips for path control \n- Think about how fun it will be to work on the task and to accomplish it \n- Always be in control of your internal state \n- Always prioritize the most important actions - be they important tasks or even micro-actions inside tasks \n- Engage in long-term thinking and planning and do not get frustrated if you are not getting results in the short-term \n- Think about all your problems as fun challenges to face \n- Embrace frustration when you're making errors and learning, this engages neuroplasticity \n \n## Questions \n- Is this the right goal? How can you make it more quantifiable? \n?? \n- Different approaches you can take to solve the problem? \na. ?? \nb. ?? \n- How would this be if this were easy? \n?? \n- What is the fastest way to get to your goal? \n?? \n- What is the least you can do to get the most results? \n?? \n- How can you eliminate this or other tasks and still achieve your mission (Subtraction)? \n?? \n- Who can I ask for help with this? \n?? \n- How can I improve through this or what new skill can I learn? \n?? \n- What problem might you encounter during this task? What is the worst decision you could possibly make? How can you screw this up? (Inversion) \n?? \n- How can you deal with them? What tests can I write? \n??"

    - trigger: ":segre"
      replace: "Segrè"

    - trigger: ":addr"
      replace: "1156 Commonwealth Avenue\nApt 26\nAllston\nMA 02134"

    - trigger: ":phone"
      replace: "8573028235"

    - trigger: ":impandas"
      replace: "import pandas as pd"

    - trigger: ":imnumpy"
      replace: "import numpy as np"

    - trigger: ":immatplotlib"
      replace: "import matplotlib.pyplot as plt"
